default:
  image: node:16

stages:
  - build
  - test
  - deploy

build_frontend:
  stage: build
  script: 
    - echo "Start building App"
    - cd frontend/
    - npm install
    - npm run build
    - echo "Build successfully!"

test_frontend:
  stage: test
  script:
    - echo "Testing App"
    - cd frontend/
    - npm install
    - CI=true npm test
    - echo "Test successfully!"

test_backend:
  stage: test
  script:
    - echo "Testing App"
    - cd backend/
    - npm install
    - CI=true npm test
    - echo "Test successfully!"

deploy_heroku_frontend:
  stage: deploy
  image: sarveen/drp12_frontend:latest
  script:
    - apt-get update -yq
    - apt-get install -y ruby
    - gem install dpl
    - cd frontend/
    - dpl --provider=heroku --app=drp12 --api-key=$HEROKU_FRONTEND_TOKEN

deploy_heroku_backend:
  stage: deploy
  image: sarveen/drp12_backend:latest
  script:
    - apt-get update -yq
    - apt-get install -y ruby
    - gem install dpl
    - cd backend/
    - dpl --provider=heroku --app=drp12-backend --api-key=$HEROKU_BACKEND_TOKEN