stages:
  - build
  - test
  - deploy

build_frontend:
  stage: build
  image: sarveen/drp12_frontend:latest
  script: 
    - echo "Start building App"
    - cd frontend/
    - npm install
    - npm run build
    - echo "Build successfully!"

test_frontend:
  stage: test
  image: sarveen/drp12_frontend:latest
  script:
    - echo "Testing App"
    - cd frontend/
    - npm install 
    - npm install @testing-library/jest-dom
    - CI=true npm test
    - echo "Test successfully!"

deploy_heroku:
  stage: deploy
  image: sarveen/drp12_frontend:latest
  script:
    - apt-get update -yq
    - apt-get install -y ruby
    - gem install dpl
    - cd frontend/
    - dpl --provider=heroku --app=drp12 --api-key=$HEROKU_TOKEN